#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common

echo "Cleaning up"
docker rm -f $NAME_SERVER || true
docker rm -f $NAME_WORKER || true
docker rm -f $NAME_REDIS || true
docker volume remove -f $NAME_VOLUME || true
ddocker network remove $NAME_NETWORK || true