#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common

function cleanup {
   . $HERE/clear_containers
}

trap cleanup EXIT

cleanup
. $HERE/run_containers

set +e
for attempt in $(seq 10); do
    echo "Attempt $attempt"
    RESPONSE=$(curl --silent http://localhost:8001)
    if [[ "$RESPONSE" == *"success"* ]]; then
        echo "SUCCESS"
        exit 0
    fi
    sleep 1
done

docker logs $NAME_SERVER
echo "FAIL"
exit 1
