#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common

# In case we switch agents between steps
[ ! -z $(docker images -q $TAG_SHA) ] || docker pull $TAG_SHA

function cleanup {
   . $HERE/clear_containers
}

trap cleanup EXIT

cleanup
. $HERE/run_containers

set +e
for attempt in $(seq 10); do
    echo "Attempt $attempt"
    RESPONSE=$(curl --silent http://localhost:8001)
    if [[ "$RESPONSE" == *"success"* ]]; then
        echo "SUCCESS"
        exit 0
    fi
    sleep 1
done

echo "FAIL"
exit 1
