# Generated by porcelain: do not edit by hand
`__porcelain__` <- function() {
  list(
    "GET /" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "GET",
        "/",
        root,
        returning = porcelain::porcelain_returning_json("root"),
        validate = validate)
    },
    "GET /metadata" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "GET",
        "/metadata",
        metadata,
        returning = porcelain::porcelain_returning_json(),
        validate = validate)
    })
}
