name: Build and push docker image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR (GitHub Packages)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: ./docker/build
      - name: Docker connection test
        run: ./docker/test_connection
      - name: Push image of branch ${{ env.BRANCH_NAME }}
        run: ./docker/push
